=begin
#Svix API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'date'
require 'time'

module Svix
  class BackgroundTaskType
    ENDPOINT_REPLAY = "endpoint.replay".freeze
    ENDPOINT_RECOVER = "endpoint.recover".freeze
    APPLICATION_STATS = "application.stats".freeze
    MESSAGE_BROADCAST = "message.broadcast".freeze
    SDK_GENERATE = "sdk.generate".freeze
    EVENT_TYPE_AGGREGATE = "event-type.aggregate".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = BackgroundTaskType.constants.select { |c| BackgroundTaskType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #BackgroundTaskType" if constantValues.empty?
      value
    end
  end
end
