=begin
#Svix API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'date'
require 'time'

module Svix
  class MessageStatus
    Success = 0.freeze
    Pending = 1.freeze
    Fail = 2.freeze
    Sending = 3.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = MessageStatus.constants.select { |c| MessageStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #MessageStatus" if constantValues.empty?
      value
    end
  end
end
