=begin
#Svix API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'date'
require 'time'

module Svix
  class TransformationHttpMethod
    POST = "POST".freeze
    PUT = "PUT".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TransformationHttpMethod.constants.select { |c| TransformationHttpMethod::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TransformationHttpMethod" if constantValues.empty?
      value
    end
  end
end
