=begin
#Svix API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'cgi'

module Svix
  class EnvironmentSettingsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get Org Settings
    # Get the environment's settings
    # @param [Hash] opts the optional parameters
    # @return [EnvironmentSettingsOut]
    def v1_environment_get_settings(opts = {})
      data, _status_code, _headers = v1_environment_get_settings_with_http_info(opts)
      data
    end

    # Get Org Settings
    # Get the environment&#39;s settings
    # @param [Hash] opts the optional parameters
    # @return [Array<(EnvironmentSettingsOut, Integer, Hash)>] EnvironmentSettingsOut data, response status code and response headers
    def v1_environment_get_settings_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EnvironmentSettingsApi.v1_environment_get_settings ...'
      end
      # resource path
      local_var_path = '/api/v1/environment/settings/'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'EnvironmentSettingsOut'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['HTTPBearer']

      new_options = opts.merge(
        :operation => :"EnvironmentSettingsApi.v1_environment_get_settings",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EnvironmentSettingsApi#v1_environment_get_settings\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
